# Matomo Release Action
# 
# Required GitHub secrets:
# 
# RELEASE_PASSWORD  |  password that needs to be provided to start the action
# GPG_CERTIFICATE  |  ASCII armored or Base64 encoded GPG certificate that is used to create the signatures for the archives
# GPG_CERTIFICATE_PASS  |  Passphrase of the GPG key

name: Build release

permissions:
  actions: none
  checks: none
  contents: write  # required to create tag and release
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Or specify a tag to build from'
        required: false
        default: ''
      password:
        description: 'Release password'
        required: true

env:
  RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check release password"
        if: ${{ github.event.inputs.password != env.RELEASE_PASSWORD }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Release password didn\'t match.')
      - name: "Check if user is allowed"
        if: ${{ github.actor != 'mattab' && github.actor != 'tsteur' && github.actor != 'justinvelluppillai' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('User is not allowed to release.')
      - uses: actions/checkout@v2
        with:
          lfs: false
      - name: Import GPG key
        id: import_gpg
        run: |
          echo "${{ secrets.GPG_CERTIFICATE }}" > $HOME/private.asc
          gpg --import --batch --yes $HOME/private.asc
          echo "default-cache-ttl 7200
          max-cache-ttl 31536000
          allow-preset-passphrase" > $HOME/.gnupg/gpg-agent.conf
          keygrip=$(gpg --import --import-options show-only --with-keygrip $HOME/private.asc | grep "Keygrip" | grep -oP "([A-F0-9]+)" | head -1)
          hexPassphrase=$( echo -n '${{ secrets.GPG_CERTIFICATE_PASS }}' | od -A n -t x1 -w100 | sed 's/ *//g' )
          gpg-connect-agent "RELOADAGENT" /bye
          gpg-connect-agent "PRESET_PASSPHRASE ${keygrip} -1 ${hexPassphrase}" /bye
          gpg-connect-agent "KEYINFO ${keygrip}" /bye
      - name: Check preconditions, create tag, build and publish release
        id: tag
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]
          then
            version="${{ github.event.inputs.version }}"
          else
            version=$(cat readme.txt | grep -oP "Stable tag:\K(.+)")
          fi
          echo "Version to build: '$version'"

          echo "Creating dedicated branch"
          git checkout develop && git pull
  
          echo "Fetching develop"
          git checkout live && git pull
          
          echo "Patch polyfills"
          wget https://github.com/matomo-org/matomo-for-wordpress/commit/bcba547f9c3185467a3f2f26d1853b2cafb62488.diff
          git apply bcba547f9c3185467a3f2f26d1853b2cafb62488.diff
          rm bcba547f9c3185467a3f2f26d1853b2cafb62488.diff
          git add app/vendor/symfony/
          git commit -m 'patch polyfills so we can release a new version and it passes WordPress file check'
          git push origin develop
  
          echo "Merge develop into live"
          git merge develop
          
          echo "Create tag"
          git fetch --tags -q 2>/dev/null
          tag_exists=$( git tag --list "$version" )

          if [[ -n "$tag_exists" ]]
          then
            echo "A tag for $tag_exists already exists."
            exit 1
          fi

          echo "Push tag"
          git commit -m "version $version"
          git push origin live
          
          echo "Creating a tag for $version"

          chmod +x ./scripts/*.sh
          ./scripts/create_tag.sh $version
          
          echo "Deploy"
          ./scripts/deploy.sh $version $SVN_USERNAME $SVN_PASSWORD
          
          echo ::set-output name=update::false
        shell: bash
      - uses: ncipollo/release-action@c4bf6c1ab090090498fb7f3ddc9f99ba5ab619b9
        with:
          artifacts: "archives/matomo-${{ steps.tag.outputs.version }}.*,archives/piwik-${{ steps.tag.outputs.version }}.*"
          allowUpdates: ${{ steps.tag.outputs.update }}
          tag: ${{ steps.tag.outputs.version }}
          body: ${{ steps.tag.outputs.body }}
          prerelease: ${{ steps.tag.outputs.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
